# NOTE 여기 까기
model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.controlnet.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image_target"  # 이거 살짝
    cond_stage_key: "image_cond"  # 여기
    control_key: "canny"  # 여기
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    # monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False

    control_stage_config:
      # NOTE: 이거 cotnrolnet 까기
      target: ldm.modules.diffusionmodules.controlnetmodel.ControlNet
      params:
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    unet_config:
      # NOTE: 이거 unet 까기
      target: ldm.modules.diffusionmodules.controlnetmodel.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      # NOTE: 이거 VAE 까기
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder

# NOTE 여기 까기
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 64
    train:
      target: ldm.data.control.ObjaverseData
      params:
        root_dir: '/mnt/datassd/seeha/data/3D/objaverse'
        txt_path: '/mnt/datassd/seeha/3DAnything/zero123/configs/train.txt'
    
    validation:
      target: ldm.data.control.ObjaverseData
      params:
        root_dir: '/mnt/datassd/seeha/data/3D/objaverse'
        txt_path: '/mnt/datassd/seeha/3DAnything/zero123/configs/val.txt'

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 16
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 16
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      every_n_train_steps: 100

  trainer:
    benchmark: True
    max_steps: 2010000
    check_val_every_n_epoch: 10